"""Shared PML command vocabulary, independent of Qt."""
KEYWORDS=set('''VAR LIST PAIRS EXIT KILL SETUP FORM LAYOUT DIALOG MAIN DOCUMENT BLOCKING
DOCK DOCKING LEFT RIGHT TOP BOTTOM FILL NONE ALL RESIZABLE SIZE TITLE
BUTTON PARAGRAPH PARA TEXT TOGGLE RTOGGLE FRAME TABSET TOOLBAR OPTION
COMBO COMBOBOX SLIDER SELECTOR DATABASE CONTAINER PMLNETCONTROL TEXTPANE
VIEW ALPHA AREA PLOT VOLUME LINE HORIZ VERT HORIZONTAL VERTICAL
AT X Y WIDTH HEIGHT BACKGROUND PIXMAP CALL CALLBACK INITCALL AUTOCALL
OKCALL CANCELCALL OK APPLY CANCEL RESET HELP NORMAL
DEFINE METHOD ENDMETHOD SHOW HIDE IS STRING REAL BOOLEAN ARRAY OBJECT
IF THEN ELSE ELSEIF ENDIF DO ENDDO FOR FROM TO BY BREAK RETURN HANDLE ENDHANDLE
AND OR NOT EQ NE GT GE LT LE
SINGLE MULTIPLE MULTI OWNERS MEMBERS AUTO ASPECT FIXCHARS
PATH HDIST HDISTANCE VDIST VDISTANCE HALIGN VALIGN CENTRE CENTER
XMIN XCEN XMAX YMIN YCEN YMAX ANCHOR NOPADDING NOALIGN AUTOALIGN
RANGE STEP NDP STATES TAG TAGWIDTH TAGWID CHANNELS REQUESTS
IMPORT USING NAMESPACE MEMBER NOBOX INDENT APPEND DELETE NEW COLLECTION
Q QUERY SAVEWORK CE END MENU ADD LIMITS SELECT REHASH LOOP EVALUATE TRACK RATE CONTENTS COMMANDS'''.split())
