import unittest
from e3d_designer.mac_import import import_mac
from e3d_designer.model import Form,Gadget,Method,Menu,MenuItem


class OutputLayoutEmptyTests(unittest.TestCase):
    def test_header_separates_both_variable_scopes_kill_and_setup(self):
        form=Form(variables={'global':'G'},local_variables={'local':'L'})
        for normalize in (False,True):
            with self.subTest(normalize=normalize):
                code=form.pml(normalize=normalize)
                expected="VAR !!global 'G'\nVAR !local 'L'\n\nkill !!userform\n\nsetup form"
                self.assertTrue(code.lower().startswith(expected.lower()))
                self.assertNotIn('-- Generated by',code);self.assertNotIn('-- Target:',code)

    def test_no_variables_means_no_leading_empty_line(self):
        self.assertTrue(Form().pml().startswith('Kill !!userform\n\nSetup Form'))
        self.assertNotIn('Define Method',Form().pml())
        self.assertNotIn('Endmethod',Form().pml())

    def test_preamble_is_preserved_and_separated_from_variables_and_kill(self):
        form=Form(variables={'global':'G'},preamble_code="-- User note\n$P 'before'")
        code=form.pml()
        self.assertIn("Var !!global 'G'\n\n-- User note\n$P 'before'\n\nKill",code)
        self.assertIn('Kill !!userform\n\nSetup Form',code)

    def test_old_generator_comments_do_not_reappear_after_import(self):
        old=("VAR !!mode 'A'\nKill !!Demo\n-- Generated by E3D PML Form Designer\n"
             "-- Target: E3D 4.0 (runtime compatibility not yet verified)\n"
             "Setup Form !!Demo Dialog\nExit\nShow !!Demo")
        code=import_mac(old).form.pml()
        self.assertIn("Var !!mode 'A'\n\nKill !!Demo\n\nSetup Form",code)
        self.assertNotIn('Generated by',code);self.assertNotIn('Target:',code)

    def test_constructor_default_helpers_and_callbacks_with_no_code_are_omitted(self):
        for body in ('',' \t\n','-- note\n$* note','$( !this.Work() $)'):
            for normalize in (False,True):
                with self.subTest(body=body,normalize=normalize):
                    form=Form(constructor_body=body,default_body=body,keep_default=True,
                              extra_methods=[Method('Empty',body=body),Method('Typed','(!arg Is String)',body)],
                              gadgets=[Gadget(name='Run',callback='Work',body=body)])
                    before=form.dumps();code=form.pml(normalize=normalize)
                    self.assertNotIn('define method',code.lower())
                    self.assertNotIn('endmethod',code.lower())
                    self.assertNotIn('callback',code.lower())
                    self.assertNotIn(' Call ',code)
                    self.assertEqual(form.dumps(),before)

    def test_empty_source_constructor_and_default_calls_are_omitted(self):
        form=Form(constructor_mode='SOURCE',constructor_body='!this.DEFAULT() -- preserved',
                  default_mode='SOURCE',keep_default=True)
        before=form.dumps();code=form.pml()
        self.assertNotIn('Define Method',code)
        self.assertNotIn('!this.DEFAULT()',code)
        self.assertEqual(form.dumps(),before)

    def test_transitive_empty_helpers_do_not_leave_calls_or_definitions(self):
        form=Form(extra_methods=[Method('One',body='!this.Two()'),Method('Two',body='-- empty')],
                  constructor_body='!this.One()',after_show_code='!this.One()',
                  gadgets=[Gadget(name='Run',callback='RunWork',body='!this.One()')])
        code=form.pml()
        self.assertNotIn('Define Method',code)
        for name in ('One','Two','RunWork'):
            self.assertNotIn('!this.'+name+'()',code)

    def test_actual_initialization_keeps_default_and_constructor(self):
        form=Form(gadgets=[Gadget(kind='text',name='Input',initial='Value')])
        code=form.pml()
        self.assertIn('Define Method .DEFAULT()',code)
        self.assertIn('Define Method .userform()',code)
        self.assertIn("!this.Input.val = 'Value'",code)
        self.assertIn('!this.DEFAULT()',code)
        self.assertLess(code.index('Define Method .DEFAULT'),code.index('Define Method .userform'))

    def test_real_helper_and_constructor_code_are_preserved(self):
        body="-- note\n$P 'keep    spacing'"
        form=Form(constructor_mode='SOURCE',constructor_body='!this.Work()',
                  extra_methods=[Method('Work',body=body)])
        code=form.pml()
        self.assertIn(body,code)
        self.assertIn('!this.Work()',code)
        self.assertIn('Define Method .userform()',code)

    def test_commands_events_pairs_and_menus_drop_only_known_empty_calls(self):
        form=Form(initcall='!this.Empty()',extra_methods=[Method('Empty')],
                  gadgets=[Gadget(name='Run',command='!this.Empty()'),
                           Gadget(kind='option',name='Pick',items=['Choice'],item_commands=['!this.Empty()'])],
                  menus=[Menu(name='Tools',items=[MenuItem('Action','!this.Empty()')])])
        code=form.pml()
        self.assertNotIn('!this.Empty()',code)
        self.assertNotIn('Define Method',code)
        self.assertIn("'Choice' ''",code)
        self.assertIn("Add 'Action' ''",code)

    def test_data_literals_other_forms_and_unknown_calls_are_preserved(self):
        body="!text = '!this.Empty()'\n!!Other.Empty()\n!this.Unknown()"
        form=Form(extra_methods=[Method('Empty')],
                  gadgets=[Gadget(name='Run',label='!this.Empty()',callback='Work',body=body)])
        code=form.pml()
        self.assertIn(body,code)
        self.assertIn("'!this.Empty()'",code)
        self.assertIn('Define Method .Work()',code)

    def test_empty_call_pruning_keeps_inline_block_comments_and_form_prefix(self):
        form=Form(name='Demo',form_prefix='.',
                  extra_methods=[Method('Empty'),Method('Work',body=".Demo.Empty() -- keep\n$( keep $) !this.Empty()\n$P 'active'")])
        code=form.pml()
        self.assertNotIn('.Demo.Empty()',code)
        self.assertNotIn('!this.Empty()',code)
        self.assertIn('-- keep',code);self.assertIn('$( keep $)',code)
        self.assertIn("$P 'active'",code)

    def test_imported_empty_callbacks_are_editable_but_not_emitted(self):
        for kind in ('Button','List','Selector','Option'):
            with self.subTest(kind=kind):
                source=(f"Setup Form !!Demo Dialog\n{kind} .Run 'Run' Call '!this.Work()'\nExit\n"
                        "Show !!Demo\nDefine Method .Work()\n-- comment\nEndmethod")
                form=import_mac(source).form
                self.assertEqual(form.named('Run').callback,'Work')
                self.assertEqual(form.named('Run').body,'-- comment')
                self.assertNotIn('!this.Work()',form.pml())
                self.assertNotIn('Define Method .Work',form.pml())
                restored=Form.loads(form.dumps());restored.named('Run').body="$P 'filled'"
                self.assertIn('Define Method .Work',restored.pml())


if __name__=='__main__':unittest.main()
