Kill !!tableDemo

Setup Form !!tableDemo Dialog Dock Right
  Title 'Multi-column LIST'
  List .equipment At X 2 Y 2 'Equipment' Single Width 50 Height 8
Exit

Show !!tableDemo

Define Method .fillEquipment()
  !HEAD = Array()
  !HEAD[1] = 'î‘çÜ'
  !HEAD[2] = 'ñºèÃ'
  !HEAD[3] = 'éÌóﬁ'
  !THIS.equipment.setheadings(!HEAD)
  !ROWS = Array()
  !ROWS[1] = Array()
  !ROWS[1][1] = 'P-101'
  !ROWS[1][2] = 'Pump 101'
  !ROWS[1][3] = 'Pump'
  !ROWS[2] = Array()
  !ROWS[2][1] = 'T-201'
  !ROWS[2][2] = 'Tank 201'
  !ROWS[2][3] = 'Tank'
  !THIS.equipment.setrows(!ROWS)
Endmethod

Define Method .tableDemo()
  !this.fillEquipment()
Endmethod
