Kill !!relativeDemo

Setup Form !!relativeDemo Dialog Dock Right
  Title 'Relative layout demo'
  Button .base At X 8 Y 3 'Base' Width 18
  Button .rightAligned At Xmax.base-Size Ymax.base+1 'Right aligned' Width 12
  Path DOWN
  Hdist 1
  Vdist 1
  Halign Centre
  Valign Top
  -- Auto placement follows rightAligned
  Button .centered  'Centered' Width 8
  Text .sameWidth At Xmin.base Ymax.centered+1 'Input' Width.base Is String
Exit

Show !!relativeDemo
