Kill !!tabdemo

Setup Form !!tabdemo Dialog Dock Right
  Title 'Tab Demo'
  Frame .tabs Tabset At X 2 Y 1 'TABSET' Width 60
    Frame .settings 'Settings'
      Text .name At X 1 Y 1 'Name' Width 24 Is String
      Option _mode At X 1 Y 3 'Mode' Call '$$_mode'
        Var List _mode Pairs
        'Mode A' |$p 'Mode A'|
        'Mode B' |$p 'Mode B'|
      Exit
    Exit
    Frame .results 'Results'
      Paragraph .message At X 1 Y 1 Text 'Results' Width 24
    Exit
  Exit
Exit

Show !!tabdemo
